stages:
  - build

build-windows:
  stage: build
  tags:
    - saas-windows-medium-amd64
  script:
    - cmake -B build -G "Visual Studio 17 2022" -A x64
    - cmake --build build --config Release -- /restore
    - mkdir dist
    - mkdir dist\Antivirus
    - xcopy build\Release\* dist\Antivirus\ /E /I /H /Y
    - del /S /Q dist\Antivirus\*.pdb
    - del /S /Q dist\Antivirus\*.lib
    - del /S /Q dist\Antivirus\*.exp
    - del /S /Q dist\Antivirus\*.ilk
    - del /S /Q dist\Antivirus\*.obj
  artifacts:
    name: "Antivirus-Executable-WinUI3"
    paths:
      - dist/
    expire_in: 1 week