[
    uuid(8a83a005-7286-42d4-ba5f-22a4d7d9a1c1),
    version(1.0)
]
interface AntivirusRpc
{
    // Передаем дескриптор связи [in] handle_t hBinding явно в функцию
    long StopAntivirusService([in] handle_t hBinding);
}