name: Build Antivirus (WinUI 3)

on:
  push:
    branches: [ "main", "task-1-gui" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build with CMake and Restore Packages
      run: cmake --build build --config Release -- /restore

    - name: Prepare Clean Package
      shell: pwsh
      run: |
        # Создаем чистую папку dist/Antivirus
        New-Item -ItemType Directory -Force -Path dist/Antivirus
        # Копируем абсолютно ВСЕ файлы и папки из Release
        Copy-Item -Path build/Release/* -Destination dist/Antivirus/ -Recurse -Force
        # Удаляем только мусор компиляции (pdb, lib, exp, obj и т.д.) во всех подпапках
        Get-ChildItem -Path dist/Antivirus -Recurse -File | Where-Object { $_.Extension -in '.pdb', '.lib', '.exp', '.obj', '.iobj', '.ipdb', '.ilk', '.recipe' } | Remove-Item -Force

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Antivirus-Executable-WinUI3
        path: dist/