name Build Antivirus (WinUI 3)

on
  push
    branches [ main, task-1-gui ]
  pull_request
    branches [ main ]

jobs
  build
    runs-on windows-latest
    
    steps
    - name Checkout repository
      uses actionscheckout@v3

    - name Configure CMake (Forcing Visual Studio Generator)
      run cmake -B build -G Visual Studio 17 2022 -A x64

    - name Build with CMake
      run cmake --build build --config Release

    - name Upload Artifact
      uses actionsupload-artifact@v3
      with
        name Antivirus-Executable-WinUI3
        path buildReleaseAntivirus.exe